version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"  # AMQP port for messaging
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  order-service:
    build: ./services/order-service
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network

  payment-service:
    build: ./services/payment-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network

  inventory-service:
    build: ./services/inventory-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge
